[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "api/functions/"


[[edge_functions]]
function = "shopping-experience"
path = "/has-something-in-cart"

[[edge_functions]]
function = "including-stuff"
path = "/stuff"

[[edge_functions]]
function = "including-stuff"
path = "/stuff"